/*
 * 
 *     Colors
 *     © Copyright 2007, Smugller
 * 
 */

#if defined _colors_included
	#endinput
#endif
#define _colors_included

#define KOLOR_NIEWIDZIALNY 0xFFFFFF00
#define KOLOR_BIALY 0xFFFFFFFF
#define KOLOR_CZARNY 0x000000FF
#define KOLOR_ZOLTY 0xFFFF00FF
#define KOLOR_POMARANCZOWY 0xFF8040FF
#define KOLOR_CZERWONY 0xFF2F2FFF
#define KOLOR_ROZOWY 0xFF80FFFF
#define KOLOR_NIEBIESKI 0x2B95FFFF
#define KOLOR_BRAZOWY 0x9D4F4FFF
#define KOLOR_ZIELONY 0x00FF40FF
#define KOLOR_TURKUSOWY 0x00FFFFFF
#define KOLOR_SZARY 0xC0C0C0FF
#define KOLOR_FILOETOWY 0x800040FF
#define KOLOR_BEZOWY 0xFFFFA6FF
#define KOLOR_BORDOWY 0x800000FF

#define C_BIALY "{FFFFFF}"
#define C_CZARNY "{000000}"
#define C_ZOLTY "{FFFF00}"
#define C_POMARANCZOWY "{FF7F50}"
#define C_CZERWONY "{FF0000}"
#define C_ROZOWY "{FF1493}"
#define C_NIEBIESKI "{4169E1}"
#define C_BRAZOWY "{A0522D}"
#define C_ZIELONY "{ADFF2F}"
#define C_TURKUSOWY "{00FFFF}"
#define C_SZARY "{C0C0C0}"
#define C_FILOETOWY "{BA55D3}"
#define C_BEZOWY "{FFDEAD}"
#define C_BORDOWY "{B22222}"