/****************************
 *                          *
 *  Include Max_Colors      *
 *    By DjGrand            *
 *      © Copyright 2010    *
 *                          *
 ****************************/

#if defined _colors_included
	#endinput
#endif
#define _colors_included

#define Bia³y 0xFFFFFFFF
#define Szary_Jasny 0xC0C0C0FF
#define Szary 0x7D7D7DFF
#define Szary_Ciemny 0x515151FF
#define Czarny 0x000000FF
#define Zolty_Jasny 0xFFFC8AFF
#define Zolty 0xFDED2BFF
#define Zolty_Ciemny 0xEEE90FFF
#define Pomaranczowy_Jasny 0xFEC754FF
#define Pomaranczowy 0xFB9626FF
#define Pomaranczowy_Ciemny 0xED6103FF
#define Czerwony_Jasny 0xFF5E5EFF
#define Czerwony 0xFF0D0DFF
#define Czerwony_Ciemny 0xC60000FF
#define Rozowy_Jasny 0xFF8CFFFF
#define Rozowy 0xFF4FFFFF
#define Rozowy_Ciemny 0xE800E8FF
#define Fioletowy_Jasny 0x9B66FFFF
#define Fioletowy 0x8518FCFF
#define Fioletowy_Ciemny 0x400080FF
#define Niebieski_Jasny 0x14FAF4FF
#define Niebieski 0x0085D5FF
#define Niebieski_Ciemny 0x0C01DEFF
#define Zielony_Jasny 0x6AFF59FF
#define Zielony 0x05E800FF
#define Zielony_Ciemny 0x008000FF
#define Braz_Jasny 0xC88235FF
#define Braz 0x844200FF
#define Braz_Ciemny 0x592D00FF
#define Bez 0xDFBFA8FF  