new WeaponList[47][32] = {
	"Piêœci",				"Kastet",				"Kij golfowy",
	"Pa³ka policyjna",		"Nó¿",					"Kij baseballowy",
	"£opata",				"Kij bilardowy",		"Katana",
	"Pi³a mechaniczna",		"Fioletowe dildo",		"Bia³e dildo",
	"D³ugie bia³e dildo",	"Bia³e dildo",			"Kwiaty",
	"Laska",				"Granaty",				"Gas ³zawi¹cy",
	"Koktail molotova",		"none",					"none",
	"none",					"Pistolet 9mm",			"Pistolet z t³umikiem",
	"Desert Eagle",			"Shotgun",				"Sawn-off Shotgun",
	"Combat Shotgun",		"Micro Uzi",			"MP5",
	"AK-47",				"M4",					"Tec9",
	"Strzelba",				"Sniper Rifle",			"RPG",
	"Wyrzutnia rakiet",		"Miotacz ognia",		"Minigun",
	"£adunki wybuchowe",	"Detonator",			"Spray",
	"Gaœnica",				"Aparat",				"Gogle noktowizyjne",
	"Gogle termiczne",		"Spadochron"
};
